"""
api_credentials.py — Credential management endpoints to integrate into main.py

These endpoints handle:
1. Generate new credentials (by HR for employee)
2. View credential audit history
3. Force password reset on next login
4. Change password (user-initiated)

Integration steps:
1. Add these endpoint functions to main.py
2. Import new schemas from schemas.py
3. Update login() to check must_reset_password flag
4. Add middleware to enforce password reset
"""

import asyncpg
import logging
from datetime import datetime
from fastapi import HTTPException
from passlib.context import CryptContext
from typing import Optional

logger = logging.getLogger("attendance")
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


# Helper: Generate temporary password (8 chars + 4 random)
def generate_temp_password() -> str:
    """Generate a random 12-character temporary password."""
    import secrets
    import string
    chars = string.ascii_letters + string.digits + "!@#$%"
    return ''.join(secrets.choice(chars) for _ in range(12))


# ══════════════════════════════════════════════════════════════
# CREDENTIAL ENDPOINTS
# ══════════════════════════════════════════════════════════════

async def generate_credentials_for_employee(
    emp_id: int,
    req: dict,  # GenerateCredentialsRequest
    hr: dict,  # from require_hr_jwt
    db: asyncpg.Connection,  # from get_db
) -> dict:
    """
    ENDPOINT: POST /api/hr/employees/{emp_id}/generate-credentials
    
    Generate new credentials for employee. Sets temporary password that
    must be reset on next login.
    
    Response includes the temporary password ONE TIME ONLY.
    """
    # Get employee and user info
    emp = await db.fetchrow(
        """SELECT e.id, e.user_id, u.email, u.full_name
           FROM employees e
           JOIN users u ON u.id = e.user_id
           WHERE e.id = $1""",
        emp_id,
    )
    if not emp:
        raise HTTPException(404, "Employee not found")
    
    user_id = emp["user_id"]
    temp_password = generate_temp_password()
    hashed = pwd_context.hash(temp_password)
    
    async with db.transaction():
        # 1. Update password hash
        await db.execute(
            "UPDATE users SET password_hash=$1, must_reset_password=TRUE WHERE id=$2",
            hashed, user_id,
        )
        
        # 2. Audit log: who generated credentials
        await db.execute(
            """INSERT INTO credential_audits 
               (user_id, action, performed_by, is_temporary, notes, created_at)
               VALUES ($1, $2, $3, TRUE, $4, NOW())""",
            user_id,
            "generated",
            hr["id"],
            req.get("notes") or f"Generated by {hr['email']}",
        )
    
    logger.info(
        "Credentials generated: emp_id=%s user_id=%s by hr_id=%s",
        emp_id, user_id, hr["id"],
    )
    
    return {
        "employee_id": emp_id,
        "email": emp["email"],
        "full_name": emp["full_name"],
        "temporary_password": temp_password,
        "must_reset_on_login": True,
        "generated_at": datetime.now().isoformat(),
        "expires_in_days": 7,
        "message": "Temporary password generated. Employee must reset on first login.",
    }


async def get_credential_audit(
    emp_id: int,
    _hr: dict,  # from require_hr_jwt
    db: asyncpg.Connection,  # from get_db
) -> dict:
    """
    ENDPOINT: GET /api/hr/employees/{emp_id}/credential-audit
    
    View credential history for employee (when password was generated, reset, etc.)
    """
    # Get user_id from employee
    emp = await db.fetchrow("SELECT user_id FROM employees WHERE id=$1", emp_id)
    if not emp:
        raise HTTPException(404, "Employee not found")
    
    user_id = emp["user_id"]
    
    # Get user details
    user = await db.fetchrow(
        """SELECT id, email, full_name, last_login, must_reset_password
           FROM users WHERE id=$1""",
        user_id,
    )
    
    # Get credential audit history
    audits = await db.fetch(
        """SELECT 
              ca.id, ca.action, ca.is_temporary, ca.performed_by,
              ca.notes, ca.created_at,
              u_perf.full_name AS performed_by_name
           FROM credential_audits ca
           LEFT JOIN users u_perf ON u_perf.id = ca.performed_by
           WHERE ca.user_id = $1
           ORDER BY ca.created_at DESC""",
        user_id,
    )
    
    audit_list = []
    for a in audits:
        audit_list.append({
            "id": a["id"],
            "action": a["action"],
            "is_temporary": a["is_temporary"],
            "performed_by_id": a["performed_by"],
            "performed_by_name": a["performed_by_name"],
            "notes": a["notes"],
            "created_at": a["created_at"].isoformat() if a["created_at"] else None,
        })
    
    return {
        "user_id": user_id,
        "email": user["email"],
        "full_name": user["full_name"],
        "must_reset_password": user["must_reset_password"],
        "last_password_change": user["last_login"].isoformat() if user["last_login"] else None,
        "last_login": user["last_login"].isoformat() if user["last_login"] else None,
        "credential_history": audit_list,
    }


async def change_password_user_initiated(
    old_password: str,
    new_password: str,
    user: dict,  # from get_current_user
    db: asyncpg.Connection,  # from get_db
) -> dict:
    """
    ENDPOINT: POST /api/auth/change-password
    
    User-initiated password change. Verify old password, set new one.
    """
    user_id = user["id"]
    
    # Get current password hash
    current_user = await db.fetchrow(
        "SELECT password_hash FROM users WHERE id=$1",
        user_id,
    )
    if not current_user:
        raise HTTPException(401, "User not found")
    
    # Verify old password
    if not pwd_context.verify(old_password, current_user["password_hash"]):
        
        # Log failed attempt
        await db.execute(
            """INSERT INTO login_audits 
               (user_id, email, success, failure_reason, created_at)
               VALUES ($1, $2, FALSE, $3, NOW())""",
            user_id, user["email"], "invalid_password_on_change",
        )
        raise HTTPException(401, "Current password is incorrect")
    
    new_hash = pwd_context.hash(new_password)
    
    async with db.transaction():
        # Update password
        await db.execute(
            """UPDATE users 
               SET password_hash=$1, must_reset_password=FALSE
               WHERE id=$2""",
            new_hash, user_id,
        )
        
        # Audit log
        await db.execute(
            """INSERT INTO credential_audits
               (user_id, action, is_temporary, created_at)
               VALUES ($1, 'changed', FALSE, NOW())""",
            user_id,
        )
    
    logger.info("Password changed: user_id=%s", user_id)
    return {
        "user_id": user_id,
        "message": "Password changed successfully",
    }


async def reset_password_by_admin(
    user_id: int,
    new_password: str,
    hr: dict,  # from require_hr_jwt
    db: asyncpg.Connection,  # from get_db
) -> dict:
    """
    ENDPOINT: POST /api/hr/users/{user_id}/reset-password
    
    Admin/HR resets user password directly.
    """
    # Verify user exists
    user = await db.fetchrow("SELECT id, email FROM users WHERE id=$1", user_id)
    if not user:
        raise HTTPException(404, "User not found")
    
    new_hash = pwd_context.hash(new_password)
    
    async with db.transaction():
        await db.execute(
            "UPDATE users SET password_hash=$1 WHERE id=$2",
            new_hash, user_id,
        )
        
        # Audit log
        await db.execute(
            """INSERT INTO credential_audits
               (user_id, action, performed_by, created_at)
               VALUES ($1, 'reset', $2, NOW())""",
            user_id, hr["id"],
        )
    
    logger.info("Password reset: user_id=%s by hr_id=%s", user_id, hr["id"])
    return {
        "user_id": user_id,
        "message": "Password reset successfully",
    }


# ══════════════════════════════════════════════════════════════
# ENHANCED LOGIN WITH CREDENTIAL TRACKING
# ══════════════════════════════════════════════════════════════

async def login_enhanced(
    email: str,
    password: str,
    db: asyncpg.Connection,
) -> dict:
    """
    Enhanced login flow with credential validation.
    
    This should REPLACE the existing login() function.
    
    Changes:
    1. Check must_reset_password flag
    2. Log login attempt (success/failure)
    3. Return flag to force password reset
    """
    email_lower = email.lower()
    
    user = await db.fetchrow(
        """SELECT id, email, password_hash, full_name, role, is_active,
                  must_reset_password
           FROM users WHERE email = $1""",
        email_lower,
    )
    
    # Log failed attempt if user not found
    if not user:
        await db.execute(
            """INSERT INTO login_audits
               (email, success, failure_reason, created_at)
               VALUES ($1, FALSE, 'user_not_found', NOW())""",
            email_lower,
        )
        raise HTTPException(401, "Invalid email or password")
    
    user_id = user["id"]
    
    # Verify password
    if not pwd_context.verify(password, user["password_hash"]):
        await db.execute(
            """INSERT INTO login_audits
               (user_id, email, success, failure_reason, created_at)
               VALUES ($1, $2, FALSE, 'invalid_password', NOW())""",
            user_id, email_lower,
        )
        raise HTTPException(401, "Invalid email or password")
    
    # Check if account is active
    if not user["is_active"]:
        await db.execute(
            """INSERT INTO login_audits
               (user_id, email, success, failure_reason, created_at)
               VALUES ($1, $2, FALSE, 'account_deactivated', NOW())""",
            user_id, email_lower,
        )
        raise HTTPException(403, "Account deactivated. Contact HR.")
    
    # Check onboarding status
    employee = await db.fetchrow(
        "SELECT onboarding_status FROM employees WHERE user_id=$1",
        user_id,
    )
    if employee and employee["onboarding_status"] != "completed":
        await db.execute(
            """INSERT INTO login_audits
               (user_id, email, success, failure_reason, created_at)
               VALUES ($1, $2, FALSE, 'onboarding_incomplete', NOW())""",
            user_id, email_lower,
        )
        raise HTTPException(
            403,
            f"Onboarding incomplete. Status: {employee['onboarding_status']}. Contact HR."
        )
    
    # Log successful login
    await db.execute(
        """UPDATE users SET last_login = NOW() WHERE id = $1""",
        user_id,
    )
    await db.execute(
        """INSERT INTO login_audits
           (user_id, email, success, failure_reason, created_at)
           VALUES ($1, $2, TRUE, NULL, NOW())""",
        user_id, email_lower,
    )
    
    logger.info("Login success: user_id=%s role=%s", user_id, user["role"])
    
    return {
        "user_id": user_id,
        "email": user["email"],
        "full_name": user["full_name"],
        "role": user["role"],
        "must_reset_password": user["must_reset_password"] or False,
    }