"""add_audit_log_snapshot_columns

Revision ID: 234bbc561a5d
Revises: 74a5f13cf063
Create Date: 2026-03-05 17:57:03.799260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '234bbc561a5d'
down_revision: Union[str, Sequence[str], None] = '74a5f13cf063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regularization_audit_logs', 'request_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('regularization_audit_logs', 'action_role',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('regularization_audit_logs', 'action_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('regularization_audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_reg_audit_created_at'), table_name='regularization_audit_logs')
    op.create_index('idx_reg_audit_created_at', 'regularization_audit_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reg_audit_created_at', table_name='regularization_audit_logs')
    op.create_index(op.f('idx_reg_audit_created_at'), 'regularization_audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('regularization_audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('regularization_audit_logs', 'action_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('regularization_audit_logs', 'action_role',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('regularization_audit_logs', 'request_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
