"""remove_paid_leave_type

Revision ID: 38d76df14b3d
Revises: fcae6a9c04b7
Create Date: 2026-03-12 19:01:01.625733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38d76df14b3d'
down_revision: Union[str, Sequence[str], None] = 'fcae6a9c04b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_leave_policy_emp'), table_name='leave_policies')
    op.drop_table('leave_policies')
    op.drop_column('leave_balances', 'total_paid_days')
    op.drop_column('leave_balances', 'used_paid_days')
    op.drop_column('leave_balances', 'remaining_paid_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_balances', sa.Column('remaining_paid_days', sa.INTEGER(), server_default=sa.text('12'), autoincrement=False, nullable=False))
    op.add_column('leave_balances', sa.Column('used_paid_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('leave_balances', sa.Column('total_paid_days', sa.INTEGER(), server_default=sa.text('12'), autoincrement=False, nullable=False))
    op.create_table('leave_policies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paid_days_per_year', sa.INTEGER(), server_default=sa.text('12'), autoincrement=False, nullable=False),
    sa.Column('effective_from', sa.DATE(), server_default=sa.text("'2024-01-01'::date"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leave_policies_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_policies')),
    sa.UniqueConstraint('employee_id', name=op.f('uq_leave_policies_employee_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_leave_policy_emp'), 'leave_policies', ['employee_id'], unique=False)
    # ### end Alembic commands ###
