"""add employees table

Revision ID: 51fe949b78b4
Revises: 786e98933b91
Create Date: 2026-02-21 16:16:48.343538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51fe949b78b4'
down_revision: Union[str, Sequence[str], None] = '786e98933b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('personal_email', sa.String(length=180), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('nationality', sa.String(length=60), nullable=True),
    sa.Column('home_address', sa.Text(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('sub_department', sa.String(length=80), nullable=True),
    sa.Column('grade', sa.String(length=30), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('cost_centre', sa.String(length=40), nullable=True),
    sa.Column('l1_manager_id', sa.Integer(), nullable=True),
    sa.Column('l2_manager_id', sa.Integer(), nullable=True),
    sa.Column('employment_type', sa.String(length=30), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('probation_end', sa.Date(), nullable=True),
    sa.Column('notice_period', sa.String(length=20), nullable=True),
    sa.Column('shift_start', sa.Time(), server_default='09:00', nullable=False),
    sa.Column('shift_end', sa.Time(), server_default='18:00', nullable=False),
    sa.Column('work_mode', sa.String(length=20), server_default='On-Site', nullable=True),
    sa.Column('weekly_off', sa.String(length=40), server_default='Saturday & Sunday', nullable=True),
    sa.Column('work_location', sa.String(length=80), nullable=True),
    sa.Column('asset_id', sa.String(length=40), nullable=True),
    sa.Column('emg_name', sa.String(length=120), nullable=True),
    sa.Column('emg_phone', sa.String(length=20), nullable=True),
    sa.Column('emg_rel', sa.String(length=40), nullable=True),
    sa.Column('annual_ctc', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pay_frequency', sa.String(length=20), server_default='Monthly', nullable=True),
    sa.Column('pf_enrolled', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('esic_applicable', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account', sa.String(length=30), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=15), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('onboarding_status', sa.String(length=20), server_default='awaiting', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("onboarding_status IN ('awaiting','in-progress','completed')", name=op.f('ck_employees_ob_status_values')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_employees_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['l1_manager_id'], ['employees.id'], name=op.f('fk_employees_l1_manager_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['l2_manager_id'], ['employees.id'], name=op.f('fk_employees_l2_manager_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employees_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('emp_id', name=op.f('uq_employees_emp_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_employees_user_id'))
    )
    op.create_index('idx_employees_branch', 'employees', ['branch_id'], unique=False)
    op.create_index('idx_employees_dept', 'employees', ['department'], unique=False)
    op.create_index('idx_employees_l1', 'employees', ['l1_manager_id'], unique=False)
    op.create_index('idx_employees_l2', 'employees', ['l2_manager_id'], unique=False)
    op.create_index('idx_employees_ob', 'employees', ['onboarding_status'], unique=False)
    op.create_index('idx_employees_user', 'employees', ['user_id'], unique=False)
    op.create_index('idx_attendance_punched_at', 'attendance_logs', ['punched_at'], unique=False)
    op.drop_index(op.f('idx_summary_date'), table_name='daily_summary')
    op.drop_index(op.f('idx_summary_user'), table_name='daily_summary')
    op.create_index('idx_summary_user_date', 'daily_summary', ['user_id', 'work_date'], unique=False)
    op.drop_index(op.f('idx_users_branch'), table_name='users')
    op.drop_constraint(op.f('users_branch_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'shift_start')
    op.drop_column('users', 'shift_end')
    op.drop_column('users', 'branch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('shift_end', postgresql.TIME(), server_default=sa.text("'18:00:00'::time without time zone"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('shift_start', postgresql.TIME(), server_default=sa.text("'09:00:00'::time without time zone"), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_branch_id_fkey'), 'users', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_users_branch'), 'users', ['branch_id'], unique=False)
    op.drop_index('idx_summary_user_date', table_name='daily_summary')
    op.create_index(op.f('idx_summary_user'), 'daily_summary', ['user_id'], unique=False)
    op.create_index(op.f('idx_summary_date'), 'daily_summary', ['work_date'], unique=False)
    op.drop_index('idx_attendance_punched_at', table_name='attendance_logs')
    op.drop_index('idx_employees_user', table_name='employees')
    op.drop_index('idx_employees_ob', table_name='employees')
    op.drop_index('idx_employees_l2', table_name='employees')
    op.drop_index('idx_employees_l1', table_name='employees')
    op.drop_index('idx_employees_dept', table_name='employees')
    op.drop_index('idx_employees_branch', table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
