"""Add audit tables and regularization improvements

Revision ID: 74a5f13cf063
Revises: ec57f64cfec4
Create Date: 2026-03-03 13:02:58.298984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a5f13cf063'
down_revision: Union[str, Sequence[str], None] = 'ec57f64cfec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regularization_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('action_by_user_id', sa.Integer(), nullable=True),
    sa.Column('action_role', sa.String(length=10), nullable=True),
    sa.Column('action_type', sa.String(length=30), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['action_by_user_id'], ['users.id'], name=op.f('fk_regularization_audit_logs_action_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['regularization_requests.id'], name=op.f('fk_regularization_audit_logs_request_id_regularization_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regularization_audit_logs'))
    )
    op.add_column('regularization_requests', sa.Column('escalation_required', sa.Boolean(), server_default='false', nullable=True))
    op.drop_constraint(op.f('uq_reg_req_employee_date'), 'regularization_requests', type_='unique')
    op.drop_column('regularization_requests', 'escalated_to_l2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regularization_requests', sa.Column('escalated_to_l2', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_reg_req_employee_date'), 'regularization_requests', ['employee_id', 'work_date'], postgresql_nulls_not_distinct=False)
    op.drop_column('regularization_requests', 'escalation_required')
    op.drop_table('regularization_audit_logs')
    # ### end Alembic commands ###
