"""Add payroll sandwich reviews table

Revision ID: 74da969e362f
Revises: 525b63bc65d0
Create Date: 2026-03-11 12:06:54.756341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74da969e362f'
down_revision: Union[str, Sequence[str], None] = '525b63bc65d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_sandwich_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('payroll_month', sa.Date(), nullable=False),
    sa.Column('sandwich_days_detected', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sandwich_pattern', sa.JSON(), nullable=True),
    sa.Column('sandwich_applied', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('decision_by_user_id', sa.Integer(), nullable=True),
    sa.Column('decision_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('sandwich_days_detected >= 0', name=op.f('ck_payroll_sandwich_reviews_sandwich_days_non_negative')),
    sa.ForeignKeyConstraint(['decision_by_user_id'], ['users.id'], name=op.f('fk_payroll_sandwich_reviews_decision_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_payroll_sandwich_reviews_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_sandwich_reviews')),
    sa.UniqueConstraint('employee_id', 'payroll_month', name='uq_sandwich_review_emp_month')
    )
    op.create_index('idx_sandwich_review_applied', 'payroll_sandwich_reviews', ['sandwich_applied'], unique=False)
    op.create_index('idx_sandwich_review_emp', 'payroll_sandwich_reviews', ['employee_id'], unique=False)
    op.create_index('idx_sandwich_review_month', 'payroll_sandwich_reviews', ['payroll_month'], unique=False)
    op.drop_index(op.f('idx_daily_summary_holiday_id'), table_name='daily_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_daily_summary_holiday_id'), 'daily_summary', ['holiday_id'], unique=False)
    op.drop_index('idx_sandwich_review_month', table_name='payroll_sandwich_reviews')
    op.drop_index('idx_sandwich_review_emp', table_name='payroll_sandwich_reviews')
    op.drop_index('idx_sandwich_review_applied', table_name='payroll_sandwich_reviews')
    op.drop_table('payroll_sandwich_reviews')
    # ### end Alembic commands ###
