"""add_leave_management

Revision ID: 8ec11a64fc03
Revises: 234bbc561a5d
Create Date: 2026-03-06 14:57:44.549538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec11a64fc03'
down_revision: Union[str, Sequence[str], None] = '234bbc561a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holiday_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('holiday_type', sa.String(length=20), server_default='national', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("holiday_type IN ('national', 'regional', 'optional')", name=op.f('ck_holiday_calendar_holiday_type_values')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holiday_calendar')),
    sa.UniqueConstraint('holiday_date', name=op.f('uq_holiday_calendar_holiday_date'))
    )
    op.create_index('idx_holiday_active', 'holiday_calendar', ['is_active'], unique=False)
    op.create_index('idx_holiday_date', 'holiday_calendar', ['holiday_date'], unique=False)
    op.create_table('leave_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_paid_days', sa.Integer(), server_default='12', nullable=False),
    sa.Column('used_paid_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('remaining_paid_days', sa.Integer(), server_default='12', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('remaining_paid_days >= 0', name=op.f('ck_leave_balances_remaining_days_non_negative')),
    sa.CheckConstraint('used_paid_days >= 0', name=op.f('ck_leave_balances_used_days_non_negative')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leave_balances_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_balances')),
    sa.UniqueConstraint('employee_id', 'year', name='uq_leave_balances_employee_year')
    )
    op.create_index('idx_leave_balance_emp', 'leave_balances', ['employee_id'], unique=False)
    op.create_index('idx_leave_balance_year', 'leave_balances', ['year'], unique=False)
    op.create_table('leave_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('paid_days_per_year', sa.Integer(), server_default='12', nullable=False),
    sa.Column('effective_from', sa.Date(), server_default='2024-01-01', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leave_policies_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_policies')),
    sa.UniqueConstraint('employee_id', name='uq_leave_policies_employee_id')
    )
    op.create_index('idx_leave_policy_emp', 'leave_policies', ['employee_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('num_days', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('l1_manager_id', sa.Integer(), nullable=True),
    sa.Column('l1_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('l1_approved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('l1_approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('l1_comment', sa.Text(), nullable=True),
    sa.Column('l2_manager_id', sa.Integer(), nullable=True),
    sa.Column('l2_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('l2_approved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('l2_approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('l2_comment', sa.Text(), nullable=True),
    sa.Column('final_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('cancelled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("final_status IN ('pending', 'approved', 'rejected', 'cancelled')", name=op.f('ck_leave_requests_leave_final_status_values')),
    sa.CheckConstraint("l1_status IN ('pending', 'approved', 'rejected')", name=op.f('ck_leave_requests_l1_leave_status_values')),
    sa.CheckConstraint("l2_status IN ('pending', 'approved', 'rejected', 'na')", name=op.f('ck_leave_requests_l2_leave_status_values')),
    sa.CheckConstraint("leave_type IN ('paid', 'unpaid')", name=op.f('ck_leave_requests_leave_type_values')),
    sa.CheckConstraint('date_from <= date_to', name=op.f('ck_leave_requests_leave_dates_order')),
    sa.CheckConstraint('num_days > 0', name=op.f('ck_leave_requests_leave_num_days_positive')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leave_requests_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['l1_approved_by_user_id'], ['users.id'], name=op.f('fk_leave_requests_l1_approved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['l1_manager_id'], ['employees.id'], name=op.f('fk_leave_requests_l1_manager_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['l2_approved_by_user_id'], ['users.id'], name=op.f('fk_leave_requests_l2_approved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['l2_manager_id'], ['employees.id'], name=op.f('fk_leave_requests_l2_manager_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], name=op.f('fk_leave_requests_submitted_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_requests'))
    )
    op.create_index('idx_leave_req_date_from', 'leave_requests', ['date_from'], unique=False)
    op.create_index('idx_leave_req_employee', 'leave_requests', ['employee_id'], unique=False)
    op.create_index('idx_leave_req_final_status', 'leave_requests', ['final_status'], unique=False)
    op.create_index('idx_leave_req_l1_manager', 'leave_requests', ['l1_manager_id'], unique=False)
    op.create_index('idx_leave_req_l2_manager', 'leave_requests', ['l2_manager_id'], unique=False)
    op.add_column('daily_summary', sa.Column('leave_request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_daily_summary_leave_request_id_leave_requests'), 'daily_summary', 'leave_requests', ['leave_request_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_daily_summary_leave_request_id_leave_requests'), 'daily_summary', type_='foreignkey')
    op.drop_column('daily_summary', 'leave_request_id')
    op.drop_index('idx_leave_req_l2_manager', table_name='leave_requests')
    op.drop_index('idx_leave_req_l1_manager', table_name='leave_requests')
    op.drop_index('idx_leave_req_final_status', table_name='leave_requests')
    op.drop_index('idx_leave_req_employee', table_name='leave_requests')
    op.drop_index('idx_leave_req_date_from', table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index('idx_leave_policy_emp', table_name='leave_policies')
    op.drop_table('leave_policies')
    op.drop_index('idx_leave_balance_year', table_name='leave_balances')
    op.drop_index('idx_leave_balance_emp', table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index('idx_holiday_date', table_name='holiday_calendar')
    op.drop_index('idx_holiday_active', table_name='holiday_calendar')
    op.drop_table('holiday_calendar')
    # ### end Alembic commands ###
