"""added is_active column in employees table

Revision ID: 8f9b4d801a3a
Revises: b90447e89381
Create Date: 2026-02-26 11:59:23.403725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9b4d801a3a'
down_revision: Union[str, Sequence[str], None] = 'b90447e89381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_employees_active', 'employees', ['is_active'], unique=False)
    op.drop_index(op.f('uq_users_email_lower'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_users_email_lower'), 'users', [sa.literal_column('lower(email::text)')], unique=True)
    op.drop_index('idx_employees_active', table_name='employees')
    # ### end Alembic commands ###
