"""Add credential management and audit tables

Revision ID: b90447e89381
Revises: 51fe949b78b4
Create Date: 2026-02-24 15:11:08.709868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90447e89381'
down_revision: Union[str, Sequence[str], None] = '51fe949b78b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('is_temporary', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("action IN ('generated','reset','regenerated','changed')", name=op.f('ck_credential_audits_credential_action_values')),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name=op.f('fk_credential_audits_performed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credential_audits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credential_audits'))
    )
    op.create_index('idx_credential_audits_created', 'credential_audits', ['created_at'], unique=False)
    op.create_index('idx_credential_audits_user', 'credential_audits', ['user_id'], unique=False)
    op.create_table('login_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('attempt_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.CheckConstraint('success IN (true, false)', name=op.f('ck_login_audits_login_success_values')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_audits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_audits'))
    )
    op.create_index('idx_login_audits_attempt', 'login_audits', ['attempt_at'], unique=False)
    op.create_index('idx_login_audits_email', 'login_audits', ['email'], unique=False)
    op.create_index('idx_login_audits_user', 'login_audits', ['user_id'], unique=False)
    op.add_column('users', sa.Column('must_reset_password', sa.Boolean(), server_default='false', nullable=True))
    op.create_index('idx_users_must_reset', 'users', ['must_reset_password'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_must_reset', table_name='users')
    op.drop_column('users', 'must_reset_password')
    op.drop_index('idx_login_audits_user', table_name='login_audits')
    op.drop_index('idx_login_audits_email', table_name='login_audits')
    op.drop_index('idx_login_audits_attempt', table_name='login_audits')
    op.drop_table('login_audits')
    op.drop_index('idx_credential_audits_user', table_name='credential_audits')
    op.drop_index('idx_credential_audits_created', table_name='credential_audits')
    op.drop_table('credential_audits')
    # ### end Alembic commands ###
