"""add uan_number to employees, update weekly_off default

Revision ID: c269fb27c986
Revises: 6da3e92e808b
Create Date: 2026-03-09 10:59:39.265456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c269fb27c986'
down_revision: Union[str, Sequence[str], None] = '6da3e92e808b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('uan_number', sa.String(length=20), nullable=True))
    op.create_unique_constraint('uq_reg_req_employee_date', 'regularization_requests', ['employee_id', 'work_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reg_req_employee_date', 'regularization_requests', type_='unique')
    op.drop_column('employees', 'uan_number')
    # ### end Alembic commands ###
