"""add regularization

Revision ID: ec57f64cfec4
Revises: 8f9b4d801a3a
Create Date: 2026-03-02 11:55:43.959456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec57f64cfec4'
down_revision: Union[str, Sequence[str], None] = '8f9b4d801a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regularization_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('actual_worked_minutes', sa.Integer(), nullable=False),
    sa.Column('requested_minutes', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('l1_manager_id', sa.Integer(), nullable=True),
    sa.Column('l1_status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('l1_approved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('l1_approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('l1_comment', sa.Text(), nullable=True),
    sa.Column('l2_manager_id', sa.Integer(), nullable=True),
    sa.Column('l2_status', sa.String(length=20), nullable=True),
    sa.Column('l2_approved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('l2_approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('l2_comment', sa.Text(), nullable=True),
    sa.Column('escalated_to_l2', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('final_status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("final_status IN ('pending', 'approved', 'rejected')", name=op.f('ck_regularization_requests_reg_final_status_values')),
    sa.CheckConstraint("l1_status IN ('pending', 'approved', 'rejected')", name=op.f('ck_regularization_requests_l1_status_values')),
    sa.CheckConstraint("l2_status IN ('pending', 'approved', 'rejected')", name=op.f('ck_regularization_requests_l2_status_values')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_regularization_requests_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['l1_approved_by_user_id'], ['users.id'], name=op.f('fk_regularization_requests_l1_approved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['l1_manager_id'], ['employees.id'], name=op.f('fk_regularization_requests_l1_manager_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['l2_approved_by_user_id'], ['users.id'], name=op.f('fk_regularization_requests_l2_approved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['l2_manager_id'], ['employees.id'], name=op.f('fk_regularization_requests_l2_manager_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], name=op.f('fk_regularization_requests_submitted_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regularization_requests')),
    sa.UniqueConstraint('employee_id', 'work_date', name='uq_reg_req_employee_date')
    )
    op.create_index('idx_reg_req_created', 'regularization_requests', ['created_at'], unique=False)
    op.create_index('idx_reg_req_employee', 'regularization_requests', ['employee_id'], unique=False)
    op.create_index('idx_reg_req_final_status', 'regularization_requests', ['final_status'], unique=False)
    op.create_index('idx_reg_req_l1_manager', 'regularization_requests', ['l1_manager_id'], unique=False)
    op.create_index('idx_reg_req_l2_manager', 'regularization_requests', ['l2_manager_id'], unique=False)
    op.create_index('idx_reg_req_work_date', 'regularization_requests', ['work_date'], unique=False)
    op.add_column('daily_summary', sa.Column('regularization_request_id', sa.Integer(), nullable=True))
    op.add_column('daily_summary', sa.Column('regularization_status', sa.String(length=20), server_default='not_requested', nullable=True))
    op.add_column('daily_summary', sa.Column('regularization_minutes', sa.Integer(), server_default='0', nullable=True))
    op.add_column('daily_summary', sa.Column('is_regularized', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('daily_summary', sa.Column('payroll_status', sa.String(length=20), server_default='absent', nullable=True))
    op.add_column('daily_summary', sa.Column('payroll_minutes', sa.Integer(), server_default='0', nullable=True))
    op.add_column('daily_summary', sa.Column('payroll_notes', sa.Text(), nullable=True))
    op.create_foreign_key(op.f('fk_daily_summary_regularization_request_id_regularization_requests'), 'daily_summary', 'regularization_requests', ['regularization_request_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_daily_summary_regularization_request_id_regularization_requests'), 'daily_summary', type_='foreignkey')
    op.drop_column('daily_summary', 'payroll_notes')
    op.drop_column('daily_summary', 'payroll_minutes')
    op.drop_column('daily_summary', 'payroll_status')
    op.drop_column('daily_summary', 'is_regularized')
    op.drop_column('daily_summary', 'regularization_minutes')
    op.drop_column('daily_summary', 'regularization_status')
    op.drop_column('daily_summary', 'regularization_request_id')
    op.drop_index('idx_reg_req_work_date', table_name='regularization_requests')
    op.drop_index('idx_reg_req_l2_manager', table_name='regularization_requests')
    op.drop_index('idx_reg_req_l1_manager', table_name='regularization_requests')
    op.drop_index('idx_reg_req_final_status', table_name='regularization_requests')
    op.drop_index('idx_reg_req_employee', table_name='regularization_requests')
    op.drop_index('idx_reg_req_created', table_name='regularization_requests')
    op.drop_table('regularization_requests')
    # ### end Alembic commands ###
