"""add_cl_sl_leave_balances

Revision ID: fcae6a9c04b7
Revises: 74da969e362f
Create Date: 2026-03-12 18:42:46.914926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcae6a9c04b7'
down_revision: Union[str, Sequence[str], None] = '74da969e362f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_balances', sa.Column('cl_total', sa.Integer(), server_default='0', nullable=False))
    op.add_column('leave_balances', sa.Column('cl_used', sa.Integer(), server_default='0', nullable=False))
    op.add_column('leave_balances', sa.Column('cl_remaining', sa.Integer(), server_default='0', nullable=False))
    op.add_column('leave_balances', sa.Column('sl_total', sa.Integer(), server_default='0', nullable=False))
    op.add_column('leave_balances', sa.Column('sl_used', sa.Integer(), server_default='0', nullable=False))
    op.add_column('leave_balances', sa.Column('sl_remaining', sa.Integer(), server_default='0', nullable=False))
    op.add_column('leave_balances', sa.Column('cl_sl_eligible', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_balances', 'cl_sl_eligible')
    op.drop_column('leave_balances', 'sl_remaining')
    op.drop_column('leave_balances', 'sl_used')
    op.drop_column('leave_balances', 'sl_total')
    op.drop_column('leave_balances', 'cl_remaining')
    op.drop_column('leave_balances', 'cl_used')
    op.drop_column('leave_balances', 'cl_total')
    # ### end Alembic commands ###
